# Generated by AI
# python -m pip install Pillow

import os
from PIL import Image

def images_to_pdf(folder_path, output_pdf_path):
    # 获取所有图像文件，并按文件名排序
    image_files = sorted(
        [f for f in os.listdir(folder_path) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
    )

    # 加载图像
    image_list = []
    for filename in image_files:
        image_path = os.path.join(folder_path, filename)
        image = Image.open(image_path).convert('RGB')  # 转换为RGB模式
        image_list.append(image)

    # 检查是否有图像
    if not image_list:
        print("没有找到图像文件。")
        return

    # 保存为PDF
    first_image = image_list[0]
    rest_images = image_list[1:]
    first_image.save(output_pdf_path, save_all=True, append_images=rest_images)
    print(f"PDF 已保存为：{output_pdf_path}")

# 示例调用
# images_to_pdf('your/image/folder/path', 'output.pdf')

images_to_pdf("./img", "output.pdf")
