# Generated by GPT-5.5

# https://dreamsavior.net/translator-plusplus/

from pathlib import Path
import csv
import shutil
from collections import Counter


# ====== 在这里设定替换对：("旧词", "新词") ======
# 会按从上到下的顺序依次替换
REPLACEMENTS = [
    ("莫妮卡", "莉娜"),
    ("モニカ", "莉娜"),
    # ("Monica", "Lina"),  # 英文名可能出现在资源名里，确认安全后再打开
]


# ====== CSV 所在文件夹 ======
FOLDER = Path.home() / "Downloads" / "TranslatorCSV"

# 如果你的 CSV 是 GBK/CP936，保持 cp936
# 如果是 UTF-8，就改成 "utf-8-sig"
ENCODING = "utf-8-sig"

# 第 1 列：Original Text
SOURCE_COL = 0

# 第 5 列：Best Translation
TARGET_COL = 4

# 是否递归处理子文件夹
RECURSIVE = True

# 是否生成 .bak 备份
MAKE_BACKUP = False

# 统计每个 key 被匹配了多少次
MATCH_COUNTER = Counter()


def replace_text(text: str) -> tuple[str, bool]:
    """按 REPLACEMENTS 依次替换，返回 替换后文本、是否发生替换。"""
    new_text = text

    for old, new in REPLACEMENTS:
        count = new_text.count(old)
        if count > 0:
            MATCH_COUNTER[old] += count
            new_text = new_text.replace(old, new)

    return new_text, new_text != text


def detect_dialect(csv_path: Path, encoding: str):
    """尽量自动识别 CSV 分隔符；失败则使用 excel 默认格式。"""
    with csv_path.open("r", encoding=encoding, newline="") as f:
        sample = f.read(4096)

    try:
        return csv.Sniffer().sniff(sample)
    except csv.Error:
        return csv.excel


def process_csv(csv_path: Path) -> tuple[int, int]:
    """处理单个 CSV，返回 总行数、修改行数。"""
    dialect = detect_dialect(csv_path, ENCODING)

    with csv_path.open("r", encoding=ENCODING, newline="") as f:
        rows = list(csv.reader(f, dialect))

    changed_count = 0

    for row in rows:
        if len(row) <= SOURCE_COL:
            continue

        source_text = row[SOURCE_COL]
        new_text, changed = replace_text(source_text)

        if changed:
            # 确保至少有 5 列
            while len(row) <= TARGET_COL:
                row.append("")

            row[TARGET_COL] = new_text
            changed_count += 1

    if changed_count > 0:
        if MAKE_BACKUP:
            backup_path = csv_path.with_suffix(csv_path.suffix + ".bak")
            if not backup_path.exists():
                shutil.copy2(csv_path, backup_path)

        with csv_path.open("w", encoding=ENCODING, newline="") as f:
            writer = csv.writer(f, dialect)
            writer.writerows(rows)

    return len(rows), changed_count


def main():
    folder = Path(FOLDER)

    if not folder.exists():
        raise FileNotFoundError(f"文件夹不存在：{folder}")

    pattern = "**/*.csv" if RECURSIVE else "*.csv"
    csv_files = sorted(folder.glob(pattern))

    if not csv_files:
        print(f"没有找到 CSV 文件：{folder}")
        return

    total_files = 0
    total_rows = 0
    total_changed = 0

    for csv_path in csv_files:
        try:
            row_count, changed_count = process_csv(csv_path)
            total_files += 1
            total_rows += row_count
            total_changed += changed_count

            print(f"[OK] {csv_path} | 行数: {row_count} | 修改: {changed_count}")

        except UnicodeDecodeError as e:
            print(f"[编码错误] {csv_path}")
            print(f"  当前 ENCODING = {ENCODING}")
            print(f"  可尝试改成 utf-8-sig、utf-8、cp932、big5")
            print(f"  详情: {e}")

        except Exception as e:
            print(f"[失败] {csv_path}: {e}")

    print()
    print("完成")
    print(f"处理文件数: {total_files}")
    print(f"总行数: {total_rows}")
    print(f"发生替换的行数: {total_changed}")

    print()
    print("关键词匹配统计:")
    for old, _new in REPLACEMENTS:
        print(f"  {old}: {MATCH_COUNTER[old]}")


if __name__ == "__main__":
    main()